### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by mileyvirus** [Belvedersky/mac-torrents#3]
Hey @Belvedersky, it looks like the script is completely broken at the moment. MTD added some new stuff: you now have to click a checkbox that dynamically shows the magnet link and it also has a password generation based on cookies that gives you the pass to open .dmg files.

**Comment by Belvedersky** [comment]
✋🏻@mileyvirus, thank you for the issue, yes this python-script broken today. MTD  added really cool protection stuff 👍🏻. Write if there are ideas as his crack without webdriver (like selenium, pupeeter).
But this pushed me to do [this](https://www.npmjs.com/package/mac-torrents) npm script. You can find this on [npm](https://github.com/Belvedersky/mac-torrents/tree/npm) brunch. 
Parser uses [this](https://www.torrentmac.net) WordPress torrents site like MTD but without protection stuff. 
But possible add another website. Like [this](https://github.com/Belvedersky/mac-torrents/blob/npm/lib/config.js) schema.

 You can test this:
 ```
npm install -g mac-torrents
mac-torrents
```
